### ISSUE TITLE
[FEATURE] Azure Active Directory B2C 

### ISSUE THREAD

**Issue by NicoCG** [maraf/FileUpload#28]
Hi @maraf,

I really like the idea of this application clean and simple.
May I ask instead of using the standard login and register functionality why not use [Azure Active Directory B2C ](https://azure.microsoft.com/en-us/services/active-directory-b2c/). 

> - Stored users—Users stored in the Azure AD B2C directory; and
> - Authentications—Tokens issued either in response to a sign-in request initiated by a user, or initiated by an application on behalf of a user (e.g. token refresh, where the refresh interval is configurable).

and the first 50000 users are free.

**Comment by maraf** [comment]
Hello!
Thanks for your interest. The answer is quite simple - Config defined user accounts are enough to what I needed. 

If your are interested in making PR with AD auth, I would gladly discuss details.
